### 1.
 Calculate the matrices representing  +90∘,  +180∘, and  −90∘ 2D rotations.

$$ R(\theta) = \begin{bmatrix} \cos \theta & -\sin \theta \\ 
 \sin \theta & \cos \theta \end{bmatrix} $$
  

1-1 +90∘
$$ R(\theta) = \begin{bmatrix} \cos +90∘ & -\sin +90∘ \\ 
 \sin +90∘ & \cos +90∘ \end{bmatrix} = \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}$$

In [1]:
import numpy as np

def rotation_matrix(degrees):
    radians = np.radians(degrees)
    c = np.cos(radians)
    s = np.sin(radians)
    R = np.array([
        [c, -s],
        [s,  c]
    ])
    return R

# Define angles
angles = [+90, +180, -90]

# Calculate and print matrices
for angle in angles:
    R = rotation_matrix(angle)
    print(f"Rotation Matrix for {angle}°:")
    print(np.round(R, decimals=3))
    print()

Rotation Matrix for 90°:
[[ 0. -1.]
 [ 1.  0.]]

Rotation Matrix for 180°:
[[-1. -0.]
 [ 0. -1.]]

Rotation Matrix for -90°:
[[ 0.  1.]
 [-1.  0.]]



### 2. 
Prove that  $R(θ)^{-1} = R(−θ)$ using linear algebra and geometric identities.

Pf)
$$
R(\theta) =
\begin{bmatrix}
\cos\theta & -\sin\theta \\\\
\sin\theta & \cos\theta
\end{bmatrix}
$$

Rotation by $-\theta$ is:

$$
R(-\theta) =
\begin{bmatrix}
\cos(-\theta) & -\sin(-\theta) \\\\
\sin(-\theta) & \cos(-\theta)
\end{bmatrix}
=
\begin{bmatrix}
\cos\theta & \sin\theta \\\\
-\sin\theta & \cos\theta
\end{bmatrix}
$$

(using $\cos(-\theta) = \cos\theta$, $\sin(-\theta) = -\sin\theta$)
For a $2 \times 2$ matrix:

$$
A = \begin{bmatrix}
a & b \\\\
c & d
\end{bmatrix}, \quad
A^{-1} = \frac{1}{ad - bc}
\begin{bmatrix}
d & -b \\\\
-c & a
\end{bmatrix}
$$

Apply to $R(\theta)$:

$$
R(\theta) =
\begin{bmatrix}
\cos\theta & -\sin\theta \\\\
\sin\theta & \cos\theta
\end{bmatrix}
$$

Determinant:

$$
\det(R(\theta)) = \cos^2\theta + \sin^2\theta = 1
$$

So the inverse is:

$$
R(\theta)^{-1} =
\begin{bmatrix}
\cos\theta & \sin\theta \\\\
-\sin\theta & \cos\theta
\end{bmatrix}
= R(-\theta)
$$

**Q.E.D.**

- Rotating by $\theta$ and then by $-\theta$ returns a point to its original position:
  
$$
R(\theta) \cdot R(-\theta) = I
$$

So:

$$
R(\theta)^{-1} = R(-\theta)
$$


### 3.
 Prove that $ R(θ_1)R(θ_2)=R(θ_1+θ_2)$ using geometric identities.

if we use trig identites, we can solve.

From trigonometry:

- $\cos(\theta_1 + \theta_2) = \cos\theta_1 \cos\theta_2 - \sin\theta_1 \sin\theta_2$
- $\sin(\theta_1 + \theta_2) = \sin\theta_1 \cos\theta_2 + \cos\theta_1 \sin\theta_2$

### 4. 
Give examples of 3D rotation matrices for which  $R_1R_2≠R_2R_1$.

 3D 회전행렬에서 $R_1 R_2 \ne R_2 R_1$ 인 예시

3차원 회전 행렬은 일반적으로 교환법칙을 만족하지 않는다.  
즉,

$$
R_1 R_2 \ne R_2 R_1
$$

가 성립한다.

예시로, 다음 두 회전 행렬을 생각해보자:

- $R_1$: x축 기준으로 $+90^\circ$ 회전
- $R_2$: y축 기준으로 $+90^\circ$ 회전

$$
R_1 =
\begin{bmatrix}
1 & 0 & 0 \\\\
0 & 0 & -1 \\\\
0 & 1 & 0
\end{bmatrix}
\quad
R_2 =
\begin{bmatrix}
0 & 0 & 1 \\\\
0 & 1 & 0 \\\\
-1 & 0 & 0
\end{bmatrix}
$$

행렬 곱 계산 결과:

$$
R_1 R_2 =
\begin{bmatrix}
0 & 0 & 1 \\\\
1 & 0 & 0 \\\\
0 & 1 & 0
\end{bmatrix}
\quad
\ne
\quad
R_2 R_1 =
\begin{bmatrix}
0 & 1 & 0 \\\\
0 & 0 & -1 \\\\
-1 & 0 & 0
\end{bmatrix}
$$




### 5. 
Prove that vector length is preserved under rotation  $∥R(θ)x∥=∥x∥$. Use this fact to prove that distance is preserved under rigid transforms.

벡터 $x$에 대해 회전 $R(\theta)$를 적용한 길이:

$$
\| R(\theta)x \|^2 = (R x)^T (R x) = x^T R^T R x = x^T I x = \| x \|^2
$$

따라서,

$$
\| R(\theta)x \| = \| x \|
$$

---

두 점 $x$, $y$에 대해 강체변환 $T(x) = R x + t$ 를 적용하면:

$$
\| T(x) - T(y) \| = \| R(x - y) \| = \| x - y \|
$$

---

결론: 회전은 벡터의 길이를 보존하고, 강체변환은 두 점 사이의 거리를 보존한다.
